### PR TITLE
v0.4.7

### LINKED ISSUE #16: NameError; is_writable
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/system.py", line 54, in is_writable
    return is_writeable(os.path.dirname(folder), check_exist)
NameError: name 'is_writeable' is not defined
```

### PR DESCRIPTION
**Pull request by stolarczyk**
fixes #16

### CODE REVIEW

**Comment by nsheff** [comment]
right, got it.

**Comment by stolarczyk** [comment]
@nsheff, I'm not a maintainer of this package on pypi, can you update it there?

**Comment by stolarczyk** [comment]
on pypi now

**Comment by nsheff** [comment]
thanks

**Comment by nsheff** [comment]
dont' forget to also draft a github release.

**Pull request merged**
