### PR TITLE
Slashes

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Comment by vreuter** [comment]
@nsheff the relevant portion of the diff is `paths.py` itself, and I guess the split of the test cases for `expandpath` into two parts, based on expected outcome. The other changes are just from moving code around.

**Comment by nsheff** [comment]
I don't quite understand -- with this change, where will we handle the double-slashes? You're just proposing to *not* handle them at all here and then let others handle them later? 

I guess that's fine, as along as there's not something that depended on this behavior downstream...given that we use attmap a lot now I'm not 100% confident about that.

**Comment by vreuter** [comment]
You wrote a comment that said to not handle them.

**Comment by nsheff** [comment]
> You wrote a comment that said to not handle them.

Oh...are you talking about this?

https://github.com/pepkit/attmap/issues/64#issuecomment-512790485

I guess -- I wrote that in July, and I was just trying to understand what you were doing here.

I guess if that made sense to me then, then probably it's the way to go.

**Review by nsheff — APPROVED** [review]

**Comment by vreuter** [comment]
Yes

**Comment by vreuter** [comment]
Sorry...not on my computer right now and so couldn’t easily find and link it

**Comment by nsheff** [comment]
No worries. I think you're right this is the way to go.

**Pull request merged**
